

version: "3.7"

services:
  flask_app:
    build: ./src
    container_name:  flask_container 
    restart: always 
    environment:
      - APP_NAME=MyFlaskApp
      - DB_USERNAME=example  
    expose:
      - 8080

  nginx: 
    build: ./nginx
    container_name: nginx_container 
    restart: always 
    ports:
      - "80:80"
    depends_on:
      - flask_app